
dependencies:
- python=3.6.2
- scikit-learn=0.24.1
- pip:
  - numpy==1.19.5
  - pandas==0.25.3
  - azureml-defaults

from azureml.core import Environment
sklearn_env = Environment.from_conda_specification(name = 'sklearn-env', file_path = './conda_dependencies.yml')
