
dependencies:
- python=3.6.2
- pip:
  - azureml-defaults
  - keras
  - tensorflow<=2.4.*
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - azureml-contrib-fairness
  - fairlearn==0.4.6
  - raiwidgets
